language: rust
matrix:
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
cache: cargo
env:
  global:
    - NDK_HOME=$HOME/android-ndk-r20
    - CC=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
    - AR=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
install: ci/install.sh
script: ci/script.sh
branches:
  only:
    - master
after_success:
  - |
      [ $TRAVIS_BRANCH = master ] &&
      [ $TRAVIS_PULL_REQUEST = false ] &&
      (cd android-ndk-sys; cargo publish --token ${CRATESIO_TOKEN})
  - |
      [ $TRAVIS_BRANCH = master ] &&
      [ $TRAVIS_PULL_REQUEST = false ] &&
      (cd android-ndk; cargo publish --token ${CRATESIO_TOKEN})
