language: rust
matrix:
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
cache: cargo
install:
  - rustup component add rustfmt
  - rustup target add arm-linux-androideabi
  - rustup target add armv7-linux-androideabi
  - rustup target add aarch64-linux-android
  - rustup target add i686-linux-android
  - rustup target add x86_64-linux-android
script: ci/script.sh
branches:
  only:
    - master
