name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-target: ['stable', 'nightly']
        rust-channel: ['arm-linux-androideabi', 'armv7-linux-androideabi', 'aarch64-linux-android', 'i686-linux-android', 'x86_64-linux-android']
    
    steps:
    - uses: actions/checkout@v1
    - name: Installing Rust ${{ matrix.rust-channel }} w/ ${{ matrix.rust-target }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-channel }}
        target: ${{ matrix.rust-target }}
        override: true
      
    - name: Download NDK
      run: |
        curl -LO https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip
        unzip android-ndk-r20-linux-x86_64.zip -d $HOME
      
    - name: Check formating
      run: cargo fmt --all -- --check
    - name: Check docs
      run: CC=cc AR=ar cargo test --manifest-path android-ndk/Cargo.toml --doc --target=x86_64-unknown-linux-gnu --features rustdoc
    - name: Run tests
      run: cargo test --package android-ndk-sys --lib --target=x86_64-unknown-linux-gnu
    - name: Check compiling on target ${{ matrix.rust-target }}
      run: cargo check --package android-ndk --target=${{ matrix.rust-target }}
